### ISSUE TITLE
Work on indentation

### ISSUE THREAD

**Issue by ghost** [HojpMania/prj-rev-bwfs-dasmoto#1]
Code indented within the div tag should be indented/aligned at the same level. Make code indentation consistent here

https://github.com/HojpMania/prj-rev-bwfs-dasmoto/blob/20c20986288a744805c9bf0c96469336f3d381a9/Dasmoto%20Project/index.html#L37-L41

**Comment by HojpMania** [comment]
Thank you for the tip
